### ISSUE TITLE
如果用escape: "javascript"会重复转义

### ISSUE THREAD

**Issue by yanhaijing** [fex-team/fis-optimizer-smarty-xss#1]
a|escape: "javascript" 编译完变成了 a|escape: "javascript"|f_escape_js  坑啊

**Comment by oxUnd** [comment]
a | escape: 'javascript' | escape: 'none'

**Comment by oxUnd** [comment]
另外，我感觉你直接上 fis 给你搞定 xss 得了；

**Comment by yanhaijing** [comment]
a|f_escape_js > a|f_escape_js
这样其实也ok，但是新手容易掉坑里
